//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Manager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Hello @Model.Name.,&lt;br /&gt;&lt;br /&gt;
        ///&lt;a style=&quot;font-size:55px;color:#C3C3C3;&quot; href=&quot;http://localhost:5742/User/Verify/@Model.GuidString&quot;&gt;Click this link to verify your vestn account!&lt;/a&gt;.
        /// </summary>
        internal static string VerifyEmailTemplate {
            get {
                return ResourceManager.GetString("VerifyEmailTemplate", resourceCulture);
            }
        }

        internal static string ForgotPasswordTemplate
        {
            get
            {
                return ResourceManager.GetString("ForgotPasswordTemplate", resourceCulture);
            }
        }

        internal static string InviteFriendTemplate
        {
            get
            {
                return ResourceManager.GetString("InviteFriendTemplate", resourceCulture);
            }
        }

        internal static string RequestBetaKeyTemplate
        {
            get
            {
                return ResourceManager.GetString("RequestBetaKeyTemplate", resourceCulture);
            }
        }

        internal static string ShareTemplate
        {
            get
            {
                return ResourceManager.GetString("ShareTemplate", resourceCulture);
            }
        }

        internal static string UserFeedbackTemplate
        {
            get
            {
                return ResourceManager.GetString("UserFeedbackTemplate", resourceCulture);
            }
        }
    }
}
