//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserClientMembers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UserClientMembers.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Websites, IT &amp; Software
        ///
        ///.NET  (355) 
        ///Active Directory  (8) 
        ///Agile Development  (4) 
        ///AJAX  (394) 
        ///Amazon Web Services  (21) 
        ///Apache  (38) 
        ///Apache Solr  (2) 
        ///Apple Safari  (3) 
        ///AS400 &amp; iSeries  (0) 
        ///ASP  (123) 
        ///Assembly  (9) 
        ///Asterisk PBX  (27) 
        ///AutoHotkey  (1) 
        ///Azure  (1) 
        ///Balsamiq  (0) 
        ///BigCommerce  (11) 
        ///Blog Install  (7) 
        ///BMC Remedy  (0) 
        ///Boonex Dolphin  (6) 
        ///Business Catalyst  (5) 
        ///C Programming  (176) 
        ///C# Programming  (180) 
        ///C++ Programming  (207) 
        ///CakePHP  (23) 
        ///Chordiant  ( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string freelancer_tags {
            get {
                return ResourceManager.GetString("freelancer_tags", resourceCulture);
            }
        }
    }
}
